### PR TITLE
missing revisions

### PR DESCRIPTION
**Pull request by sooorajjj**
no branch named kitkat1
*https://github.com/ResurrectionRemix/android_packages_services_Telephony
*https://github.com/ResurrectionRemix/android_packages_apps_LockClock
*https://github.com/ResurrectionRemix/android_device_lge_hammerhead

causing repo sync to stop

### CODE REVIEW

**Comment by sooorajjj** [comment]
screenshot from 2015-03-07 22 45 51

**Comment by westcripp** [comment]
kitkat branch is broken

**Comment by sooorajjj** [comment]
ya sadly ... totally broken

**Comment by sooorajjj** [comment]
if you have removed support for kitkat then why is the branch still shown in manifest pls remove it so other users don have same problems

**Comment by Furrydaus** [comment]
Well thats the owners decision to do so. Youll never know if someone could fix in time. Thats why most of the platform manifest files have been tweaked for lollipop, to promote the use of the latest tech

**Comment by sooorajjj** [comment]
Lol if Kitkat support has been removed ... i would say that was done on a purpose they have deleted the branch kitkat from many repo ........ which directly says it they dont want kitkat support anymore

**Comment by Furrydaus** [comment]
Well leaving it there wouldn't hurt right? XD

**Comment by sooorajjj** [comment]
LOL ....... there is no meaning in leaving it here ..... 
some users like me will try to sync it and all it will give is fetch errors after say 4-5hrs of sync waste of time and data

**Comment by westcripp** [comment]
im stopped build rom since android version 4.4.2 so its impossible to keep it up to date kitkat1 branch . so why you want to build kitkat ?

**Comment by sooorajjj** [comment]
because you had Kitkat branch in your manifest

**Comment by Furrydaus** [comment]
Manifests are manifests dude

**Comment by sooorajjj** [comment]
Anyway it upto you what ever you decide 
its just one user opinion

**Comment by westcripp** [comment]
kitkat branch just removed

**Comment by dumtara** [comment]
sooorajjj is correct. These should be fixed.

**Comment by Furrydaus** [comment]
Kitkat Branch has been removed. @westcripp  I recommend doing the same for almost all the repo's available in case some dumb people come round. XD

**Comment by sooorajjj** [comment]
@Furrydaus  kitkat branch was already removed from rest of the repo's lol

**Comment by Furrydaus** [comment]
@sooorajjj  Then that's good hahahhaa no more confusion :+1:

**Pull request closed without merging**
