### PR TITLE
5.1.1_r4

### PR DESCRIPTION
**Pull request by Furrydaus**

### CODE REVIEW

**Comment by akhilnarang** [comment]
@Furrydaus  CM also haven't updated yet

**Comment by Furrydaus** [comment]
Yeah just noticed.

**Comment by akhilnarang** [comment]
LoL

**Comment by Furrydaus** [comment]
Just a bit excited to going for the r4 branch haha

**Comment by akhilnarang** [comment]
ok, wait will they update manifest and all their repos, then :P

**Pull request closed without merging**
