### PR TITLE
Added updated setup.sh for setting up stuff

### PR DESCRIPTION
**Pull request by regalstreak**
for our new buddies out there :)
Am working on build.sh

### CODE REVIEW

**Comment by regalstreak** [comment]
@akhilnarang @varund7726 @westcripp

**Comment by regalstreak** [comment]
build.sh needed no changes

**Comment by akhilnarang** [comment]
Will be added later
@furrydaus is working on a better version
Guys can't be so lazy anyway, all command are given, just need to copy paste

**Comment by regalstreak** [comment]
kek

**Comment by Furrydaus** [comment]
Btw @regalstreak its already here :)

https://github.com/ResurrectionRemix/ResurrectedScripts

**Comment by regalstreak** [comment]
Aah. @akhilnarang why didnt you tell me this :/

**Comment by Furrydaus** [comment]
@regalstreak

I just released alongside akhil haha

**Comment by regalstreak** [comment]
dayum

**Pull request closed without merging**
