### PR TITLE
Use phablet tools for repo stuff

### PR DESCRIPTION
**Pull request by nilac8991**
- Phablet tools already includes repo so why don't we use it? There is no more reason to set up manually as apt does everything for you

Signed-off-by: Calin Neamtu nilac8991@gmail.com

### CODE REVIEW

**Comment by akhilnarang** [comment]
@nilac8991 phablet-tools had an outdated version last time I checked :p 
I'll check again how it is now

**Comment by akhilnarang** [comment]
Tested again, it still gives an older version ;_;
Sorry :p

**Comment by nilac8991** [comment]
Nah it's fine, but i will try to see if i could do a sort of ppa for all these sort of things in order to don't install all these stuff manually... Just one command and that's all

**Comment by sea51930** [comment]
Călin Neamţu notifications@github.com 於 2016年3月7日 週一 05:42 寫道：

> - Phablet tools already includes repo so why don't we use it? There is
>   no more reason to set up manually as apt does everything for you
> 
> ## Signed-off-by: Calin Neamtu nilac8991@gmail.com
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/ResurrectionRemix/platform_manifest/pull/65
> Commit Summary
> - Use phablet tools for repo stuff
> 
> File Changes
> - _M_ README.mkdn
>   https://github.com/ResurrectionRemix/platform_manifest/pull/65/files#diff-0
>   (17)
> 
> Patch Links:
> - https://github.com/ResurrectionRemix/platform_manifest/pull/65.patch
> - https://github.com/ResurrectionRemix/platform_manifest/pull/65.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ResurrectionRemix/platform_manifest/pull/65.
> 
> ## 

Gmail fromsea51930@gmail.com
Paypalsea51930@gmail.com

**Pull request closed without merging**
