### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by akhilnarang**
Option to enter number of jobs, and whether to sync now or later

### CODE REVIEW

**Comment by Furrydaus** [comment]
Nice. @westcripp You might wanna add this.
@akhilnarang Change the Variable "Jobs" to something more user friendly :)

**Comment by akhilnarang** [comment]
@Furrydaus  change it to what?:P
The user most probably won't examine the contents of the script

**Comment by Furrydaus** [comment]
@akhilnarang You can use the script. Its open source anyway.

**Comment by akhilnarang** [comment]
Okay thanks

**Pull request merged**
