### PR TITLE
Merge Android 8.1.0_r14

### PR DESCRIPTION
**Pull request by pomelohan**

### CODE REVIEW

**Comment by akhilnarang** [comment]
What?

**Comment by pomelohan** [comment]
Merge the latest Android source code

**Comment by pomelohan** [comment]
Any problem?

**Comment by akhilnarang** [comment]
That is not how to do it, it needs to be merged in all other repositories too. And higher number dosen't always mean latest.

**Comment by pomelohan** [comment]
Just update manifest

**Comment by msfjarvis** [comment]
That's not how it works genius

**Comment by pomelohan** [comment]
My mistake.Closed.

**Pull request closed without merging**
