### PR TITLE
manifest: Merge upstream changes from LineageOS

### PR DESCRIPTION
**Pull request by HridayHS**
Give some life to Marshmallow users. :)

### CODE REVIEW

**Comment by HridayHS** [comment]
Everything is tested and working perfectly.

Vendor pull reuqest: https://github.com/ResurrectionRemix/android_vendor_resurrection/pull/74
frameworks/base: https://github.com/ResurrectionRemix/android_frameworks_base/pull/178
android_build: https://github.com/ResurrectionRemix/android_build/pull/25

Other repos are forked and I can't pull request to them so need some help to update them.

Here the updated repos:-

LockClock: https://github.com/HridayHS/android_packages_apps_LockClock/tree/marshmallow
PackageInstaller: https://github.com/HridayHS/android_packages_apps_PackageInstaller
ThemeManagerService: https://github.com/HridayHS/android_packages_services_ThemeManagerService
cm_platform_sdk: https://github.com/HridayHS/cm_platform_sdk/tree/marshmallow
system_core: https://github.com/HridayHS/system_core/tree/marshmallow
Telephony: https://github.com/HridayHS/android_packages_services_Telephony/tree/marshmallow
Telecomm: https://github.com/HridayHS/android_packages_services_Telecomm/tree/marshmallow
SetupWizard: https://github.com/HridayHS/android_packages_apps_SetupWizard
Messaging: https://github.com/HridayHS/android_packages_apps_Messaging/tree/marshmallow
InCallUI: https://github.com/HridayHS/android_packages_apps_InCallUI
CMFileManager: https://github.com/HridayHS/packages_apps_CMFileManager

**Comment by westcripp** [comment]
link your other repositories to rr m manifest than do pull request   i will merge

**Comment by westcripp** [comment]
if all working without issues

**Comment by HridayHS** [comment]
Ok

**Comment by GMCadiom** [comment]
+1 @westcripp 
merge those commits 
it worked with me good from yesterday and stable till now 

nice info to share bro @HridayHS

**Comment by varund7726** [comment]
@GMCadiom they will have to make a pull request first .we can only merge them of that happens

**Comment by GMCadiom** [comment]
@varund7726 
so if i made it can u merge it to make the source alive again ??

**Comment by varund7726** [comment]
Yes

**Comment by HridayHS** [comment]
Everything fine now. RR-MM live again. <3

**Pull request merged**
