### PR TITLE
5.1.1_r6 -> 5.1.1_r13

### PR DESCRIPTION
**Pull request by nilac8991**
Change-Id: I89604028a81a507118266dac5427e9b46d2d7d2c
Signed-off-by: nilac8991 nilac8991@gmail.com

### CODE REVIEW

**Comment by akhilnarang** [comment]
Wait for CM :P

**Comment by nilac8991** [comment]
Ok as you wish :p

**Comment by varund7726** [comment]
@nilac8991 the reason is because right now in fw base we have too many code conflicts with anything after r6.
Once cm merges it, conflicts will be much easier to solve

**Comment by nilac8991** [comment]
Ok,  no problem @varund7726 :)

**Pull request closed without merging**
